name: Mobile App

on: [push]

jobs:
  Build:
    runs-on: [self-hosted, macos]

    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
      - name: Prepare Env
        run: |
          cp ~/dev/secrets/corona-app/Corona\ FCM.plist frontend/corona_tracker/ios/Runner/GoogleService-Info.plist
          cp ~/dev/secrets/corona-app/Corona\ FCM.json frontend/corona_tracker/android/app/google-services.json
          cp ~/dev/secrets/corona-app/Corona\ Playstore.json frontend/corona_tracker/android/playstore-serviceaccount.json
          cp ~/dev/secrets/corona-app/Corona\ Android\ Keystore.properties frontend/corona_tracker/android/key.properties

      - name: Bundle Android AppBundle
        run: cd frontend/corona_tracker/ && flutter build appbundle --target-platform android-arm,android-arm64,android-x64
      - name: Bundle iOS App
        run: cd frontend/corona_tracker/ && flutter build ios --release --no-codesign
      - name: Publish Preview
        run: |
          (cd frontend/corona_tracker/android && fastlane install_plugins && fastlane alpha)
          (cd frontend/corona_tracker/ios && fastlane install_plugins && fastlane alpha)
        #if: contains( github.ref, 'develop' ) || contains( github.base_ref, 'develop' )
      - uses: actions/upload-artifact@v1
        with:
          name: IPA
          path: frontend/corona_tracker/ios/Corona\ Track.ipa
        #if: contains( github.ref, 'develop' ) || contains( github.base_ref, 'develop' )
      - uses: actions/upload-artifact@v1
        with:
          name: AAB
          path: frontend/corona_tracker/build/app/outputs/bundle/release/app-release.aab
        #if: contains( github.ref, 'develop' ) || contains( github.base_ref, 'develop' )
