name: Mobile App

on: [push]

jobs:
  Build:
    runs-on: [self-hosted, macos]

    steps:
      - uses: actions/checkout@v1
      - name: Prepare Env
        run: cp ~/dev/secrets/corona-app/Corona\ FCM.plist frontend/corona_tracker/ios/Runner/GoogleService-Info.plist && cp ~/dev/secrets/corona-app/Corona\ FCM.json frontend/corona_tracker/android/app/google-services.json
      - name: Bundle APK
        run: cd frontend/corona_tracker/ && flutter build appbundle --target-platform android-arm,android-arm64,android-x64
      - name: Bundle IPA
         run: cd frontend/corona_tracker/ && flutter build ios
